# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    statehandler:
        class: AppBundle\Service\StateHandler
        arguments: ['@doctrine.orm.entity_manager',"id",]
